version: '3.9'  # Esta línea es opcional, pero recomendable para versión de sintaxis

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www                # Monta el código local dentro del contenedor
    expose:
      - "9000"                   # Expone internamente el puerto 9000 (PHP-FPM)
    depends_on:
      - redis
    networks:
      - laravel                 # Define que este servicio está en la red 'laravel'

  webserver:
    image: nginx:alpine
    container_name: laravel_webserver
    restart: unless-stopped
    ports:
      - "8080:80"               # Mapea puerto 80 del contenedor al 8080 del host
    volumes:
      - .:/var/www              # Monta el código local para servir con nginx
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro  # Config nginx
    depends_on:
      - app
    networks:
      - laravel

  vite:
    image: node:18
    container_name: vite_dev
    working_dir: /var/www
    volumes:
      - .:/var/www
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"              # Para el servidor de desarrollo Vite
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5432:5432"              # Mapea postgres para poder conectarte desde host si quieres
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data  # Volumen persistente para los datos de postgres
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - laravel

# Aquí defines la red que usarán tus contenedores
networks:
  laravel:
    driver: bridge

# Aquí defines los volúmenes nombrados (persistencia de datos)
volumes:
  db_data:
